[project]
name = "easy_prompt"
version = "1.0.0"
description = "A project making LLM prompting easy."
authors = [
    {name = "Leonardo Mieschendahl", email = "miesschendahl.leonardo@gmail.com"}
]
dependencies = ['openai >=1.83.0, <2.0.0']

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"